// <auto-generated />
using System;
using MiWebAPIFotos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiWebAPIFotos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117213645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiWebAPIFotos.Entities.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Pagada")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitaId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("MiWebAPIFotos.Entities.Seleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitaId");

                    b.ToTable("Selecciones");
                });

            modelBuilder.Entity("MiWebAPIFotos.Entities.SeleccionFoto", b =>
                {
                    b.Property<int>("SeleccionId")
                        .HasColumnType("int");

                    b.Property<int>("FotoId")
                        .HasColumnType("int");

                    b.HasKey("SeleccionId", "FotoId");

                    b.HasIndex("FotoId");

                    b.ToTable("SeleccionFotos");
                });

            modelBuilder.Entity("MiWebAPIFotos.Entities.Visita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("MiWebAPIFotos.Entities.Foto", b =>
                {
                    b.HasOne("MiWebAPIFotos.Entities.Visita", "Visita")
                        .WithMany("Fotos")
                        .HasForeignKey("VisitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("MiWebAPIFotos.Entities.Seleccion", b =>
                {
                    b.HasOne("MiWebAPIFotos.Entities.Visita", "Visita")
                        .WithMany("Selecciones")
                        .HasForeignKey("VisitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("MiWebAPIFotos.Entities.SeleccionFoto", b =>
                {
                    b.HasOne("MiWebAPIFotos.Entities.Foto", "Foto")
                        .WithMany("SeleccionFotos")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiWebAPIFotos.Entities.Seleccion", "Seleccion")
                        .WithMany("SeleccionFotos")
                        .HasForeignKey("SeleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Seleccion");
                });

            modelBuilder.Entity("MiWebAPIFotos.Entities.Foto", b =>
                {
                    b.Navigation("SeleccionFotos");
                });

            modelBuilder.Entity("MiWebAPIFotos.Entities.Seleccion", b =>
                {
                    b.Navigation("SeleccionFotos");
                });

            modelBuilder.Entity("MiWebAPIFotos.Entities.Visita", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Selecciones");
                });
#pragma warning restore 612, 618
        }
    }
}
